# Generated by Django 5.1 on 2024-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="created_at",
            new_name="create_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(
                blank=True, default="Programming", related_name="tag", to="api.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
