# Generated by Django 5.1 on 2024-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_created_at_tag_create_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(
                blank=True, default="Programming", to="api.tag"
            ),
        ),
    ]
